# Generated by Django 5.2.1 on 2025-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
