# Generated by Django 5.2.1 on 2025-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
