# Generated by Django 5.2.1 on 2025-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exercise_userexerciserelation_exercise_sportsman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='burn_calories',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
