# Generated by Django 5.2.1 on 2025-05-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_exercise_burn_calories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexerciserelation',
            old_name='in_bookmarks',
            new_name='in_exercisemarks',
        ),
    ]
