# Generated by Django 5.2.1 on 2025-05-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_in_bookmarks_userexerciserelation_in_exercisemarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexerciserelation',
            name='rate',
        ),
    ]
