# Generated by Django 5.2.1 on 2025-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='nameTag',
            field=models.CharField(default='default_tag', max_length=100),
        ),
    ]
