# Generated by Django 5.2.1 on 2025-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_activity_level_profile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('n/a', 'N/A')], default='n/a', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
